---
- name: Testing andrewrothstein.trivy
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'trivy --version'
      ansible.builtin.command: trivy --version
      changed_when: false
      register: trivy_test_output
    - name: Output from 'trivy --version'
      ansible.builtin.debug:
        msg: '{{ trivy_test_output.stdout }}'
