---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/trivy --version
      register: trivy_test_output
    - debug:
        msg: '{{ trivy_test_output.stdout }}'
